# Generated by Django 3.0.5 on 2020-05-09 10:18

from django.db import migrations, models
import stacklion.models


class Migration(migrations.Migration):

    dependencies = [
        ('stacklion', '0004_auto_20200508_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to=stacklion.models.user_directory_path),
        ),
    ]
