# Generated by Django 3.0.5 on 2020-07-10 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacklion', '0007_auto_20200517_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_file',
        ),
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='stacklion.Question')),
            ],
        ),
    ]
