# Generated by Django 3.0.5 on 2020-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('end_date', models.DateField()),
                ('check', models.BooleanField(default=False)),
            ],
        ),
    ]
