# Generated by Django 3.0.5 on 2020-08-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfiles',
            name='fileName',
            field=models.TextField(default='hi'),
        ),
    ]
