# Generated by Django 3.0.5 on 2020-07-14 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(verbose_name='date published')),
                ('register_content', models.TextField(blank=True, null=True)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='hw.Homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='hw.Submission')),
            ],
        ),
    ]
