# Generated by Django 3.0.5 on 2020-07-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0002_submission_submissionfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
