# Generated by Django 3.0.5 on 2020-07-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0004_homework_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='author',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='confirm',
        ),
    ]
