# Generated by Django 3.0.5 on 2020-08-05 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0005_auto_20200728_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='homework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='hw.Homework'),
        ),
        migrations.AlterField(
            model_name='submissionfiles',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hw.Submission'),
        ),
    ]
