# Generated by Django 2.2.11 on 2020-06-29 10:19

from django.db import migrations, models
import homework.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
