# Generated by Django 2.2.11 on 2020-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_post_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
