# Generated by Django 2.2.11 on 2020-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_remove_notice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='submitdate',
            field=models.DateTimeField(default='1950-01-01'),
        ),
    ]
