# Generated by Django 2.2.11 on 2020-07-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_notice_submitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='submitdate',
            field=models.DateTimeField(verbose_name='publish'),
        ),
    ]
