# Generated by Django 2.2.11 on 2020-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_auto_20200701_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publication_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
