# Generated by Django 2.2.11 on 2020-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_auto_20200701_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='submitdate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publication_day',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publication_month',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='notice',
            name='publication_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='publication_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
