# Generated by Django 2.2.11 on 2020-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_auto_20200701_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='publication_day',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='publication_month',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='publication_year',
        ),
        migrations.AddField(
            model_name='notice',
            name='submitdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
