# Generated by Django 3.0.5 on 2020-07-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0011_auto_20200701_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
